endpointUrl = "https://dog.ceo/api"
resourcePath = "/breeds/list/all"

## These values are only required for OAuth2 authentication
tokenUrl = "add-the-token-url"
clientId = "add-the-client-id"
clientSecret = "add-the-client-secret"
